### ISSUE TITLE
diverging from original types

### ISSUE THREAD

**Issue by adbenitez** [webxdc/webxdc-types#1]
the updated versions are at https://github.com/webxdc/hello (webxdc.js and webxdc.d.ts files)

this project is creating a completely new file which has extra maintenance cost, couldn't this project just host the mentioned files then it would be easier for other projects to use this package as a dev dependency in package.json without having to include the file in their repository and manually updating it from time to time

**Comment by Simon-Laux** [comment]
fixed by #2
